const views=[...document.querySelectorAll('.view')];
const header=document.querySelector('.site-header');
function showView(id){views.forEach(v=>v.classList.toggle('active-view',v.id===id));header.style.display=['discover','researching'].includes(id)?'none':'';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>{resetInterview();showView('discover')}));
document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>showView('home')));
document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>showView('discover')));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showView(b.dataset.view)}));

const steps=[
  {key:'lifestyle',icon:'◒',label:'LIFESTYLE',question:'What would make an ordinary day there feel exactly right?',choices:['Sailing, swimming & local food','Nature, privacy & long walks','Culture, restaurants & a social scene'],answer:'Sea, sailing, local food',reply:'That suggests a place where the water is part of daily life—not just a view.'},
  {key:'season',icon:'☀',label:'SEASON',question:'When would you use the home most?',choices:['May — September','School holidays year-round','Winter sun','Several short stays'],answer:'May — September',reply:'I’ll prioritise a strong summer season and places that still feel authentic beyond August.'},
  {key:'party',icon:'♙',label:'TRAVELLING PARTY',question:'Who should the home work comfortably for?',choices:['A couple + adult children','Family with young children','Mostly a couple','Friends and extended family'],answer:'Couple + adult children',reply:'So privacy for you, plus proper guest rooms for visits—not unused space all year.'},
  {key:'access',icon:'↗',label:'ACCESS',question:'How much travel friction is acceptable from London?',choices:['Up to 6 hours door-to-door','Up to 8 hours is fine','Direct flight is essential','Travel time is flexible'],answer:'Up to 8 hours',reply:'That keeps islands with a short ferry transfer in play, while excluding difficult multi-stop routes.'},
  {key:'budget',icon:'€',label:'BUDGET',question:'What purchase budget feels comfortable for a ready home?',choices:['Up to €1.5M','€1.5M — €3M','€3M — €5M','Still exploring'],answer:'€1.5M — €3M',reply:'I’ll treat €3M as a firm ceiling and explain when a compromise creates better value.'},
  {key:'home',icon:'◇',label:'HOME',question:'What does the home itself need to provide?',choices:['3+ beds · Ready · Sea view','4+ beds · Pool · Privacy','2+ beds · Walk to town','I’m open to suggestions'],answer:'3+ beds · Ready · Sea view',reply:'Ready to move in, at least three bedrooms and a meaningful sea connection. No renovation projects.'},
  {key:'location',icon:'⌖',label:'LOCATION',question:'Based on everything you’ve told me, these three destinations stand out. Where should we begin?',choices:['Hydra, Greece','Sóller, Mallorca','Hvar, Croatia','Show different locations'],answer:'Hydra, Greece',reply:'Hydra is the strongest starting point: car-free, sociable, deeply connected to the sea, and reachable from Athens. Its main compromise is limited ready-home inventory.'}
];
let currentStep=0, profile={};
const messages=document.querySelector('#messages'),suggestions=document.querySelector('#suggestions'),profileFields=document.querySelector('#profileFields');
function resetInterview(){currentStep=0;profile={};messages.innerHTML='<div class="day-label">TODAY</div><div class="message ai"><img src="assets/Symbol.svg" alt=""><div><p>Let’s begin with the life, not the property.</p><p>Tell me what your ideal life in a home abroad looks like—how would you spend a typical day there?</p></div></div><div class="suggestions" id="suggestions"></div>';renderProfile();renderChoices()}
function renderProfile(){
  profileFields.innerHTML=steps.map((s,i)=>{const done=profile[s.key];const active=i===currentStep;return `<button class="profile-row ${done?'confirmed':active?'proposed':'missing'}"><span class="profile-icon">${s.icon}</span><span><small>${s.label}</small><b>${done|| (active?'Being discussed':'Not determined')}</b></span><i>${done?'✓':active?'AI':'+'}</i></button>`}).join('');
  const pct=Math.round(Object.keys(profile).length/steps.length*100);document.querySelector('#clarity').textContent=pct+'%';document.querySelector('#progressBar').style.width=pct+'%';
}
function renderChoices(){const box=document.querySelector('#suggestions');if(!box)return;box.innerHTML=steps[currentStep].choices.map(x=>`<button>${x}</button>`).join('')}
messages.addEventListener('click',e=>{if(e.target.closest('.suggestions button'))choose(e.target.textContent);if(e.target.closest('[data-research]'))startResearch()});
document.querySelector('#chatForm').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#chatInput');if(input.value.trim())choose(input.value.trim());input.value=''});
function choose(text){
  const step=steps[currentStep];profile[step.key]=text.includes('explor')?step.answer:text;
  document.querySelector('#suggestions')?.remove();messages.insertAdjacentHTML('beforeend',`<div class="message user"><div>${text}</div></div>`);renderProfile();
  setTimeout(()=>{if(currentStep<steps.length-1){currentStep++;messages.insertAdjacentHTML('beforeend',`<div class="message ai"><img src="assets/Symbol.svg" alt=""><div><p>${step.reply}</p><p>${steps[currentStep].question}</p></div></div><div class="suggestions" id="suggestions"></div>`);renderProfile();renderChoices()}else{messages.insertAdjacentHTML('beforeend',`<div class="message ai"><img src="assets/Symbol.svg" alt=""><div><p>${step.reply}</p><div class="profile-confirm"><small>SEARCH PROFILE READY</small><b>Hydra · €1.5M—€3M · 3+ bedrooms · Summer</b><span>Sources and freshness will be included. Research takes 15 seconds in this prototype.</span></div><button class="primary-button" data-research>Start location research <span>↗</span></button></div></div>`);currentStep++;renderProfile()}messages.scrollTop=messages.scrollHeight},260)
}

let researchInterval;
function startResearch(){
  clearInterval(researchInterval);document.querySelector('[data-research]')?.remove();
  messages.insertAdjacentHTML('beforeend',`<div class="message ai thinking-message"><img src="assets/Symbol.svg" alt=""><div class="chat-thinking"><div class="thinking-line"><span class="thinking-orb"></span><b id="chatResearchStatus">Researching Hydra…</b><em id="chatResearchTimer">15s</em></div><div class="thinking-summary"><span id="chatResearchAction">Resolving the location and nearby areas</span><small><b id="chatSources">0</b> sources · <b id="chatPages">0</b> pages · <b id="chatListings">0</b> listings · <b id="chatDupes">0</b> duplicates</small></div></div></div>`);messages.scrollTop=messages.scrollHeight;
  const started=Date.now(),duration=15000,targets={chatSources:38,chatPages:124,chatListings:24,chatDupes:7};
  const labels=['Resolving Hydra and nearby areas…','Discovering reliable open-web sources…','Reading climate, access and ownership information…','Extracting and normalizing ready-home listings…','Merging duplicate properties across brokers…','Matching homes to your Search Profile…'];
  const tick=()=>{const elapsed=Date.now()-started,p=Math.min(elapsed/duration,1),stage=Math.min(Math.floor(p*6),5);document.querySelector('#chatResearchTimer').textContent=Math.max(0,Math.ceil((duration-elapsed)/1000))+'s';document.querySelector('#chatResearchAction').textContent=labels[stage];Object.entries(targets).forEach(([id,val])=>document.querySelector('#'+id).textContent=Math.floor(val*Math.min(1,p*1.16)));if(p>=1){clearInterval(researchInterval);document.querySelector('.thinking-orb').classList.add('complete');document.querySelector('#chatResearchTimer').textContent='Done';document.querySelector('#chatResearchStatus').textContent='Research complete';document.querySelector('#chatResearchAction').textContent='38 sources checked · 17 matching homes ready';document.querySelector('.thinking-summary small').style.display='none';setTimeout(()=>{messages.insertAdjacentHTML('beforeend',`<div class="message ai"><img src="assets/Symbol.svg" alt=""><div><p>Your Hydra research is ready. I found a strong lifestyle fit, but also two compromises worth seeing clearly.</p><button class="primary-button" data-open-results>View location intelligence <span>↗</span></button></div></div>`);messages.scrollTop=messages.scrollHeight},400)}};tick();researchInterval=setInterval(tick,100);
}

document.querySelectorAll('[data-activity-filter]').forEach(button=>button.addEventListener('click',()=>{const category=button.dataset.activityFilter;document.querySelectorAll('[data-activity-filter]').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.activity-card').forEach(card=>card.classList.toggle('filtered-out',category!=='all'&&card.dataset.category!==category))}));
document.querySelectorAll('.activity-more').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.activity-card'),open=card.classList.toggle('expanded');button.innerHTML=open?'Hide details <span>↑</span>':'See details <span>↓</span>'}));
messages.addEventListener('click',e=>{if(e.target.closest('[data-open-results]'))showView('results')});

const overlay=document.querySelector('#contactOverlay'),contactTitle=document.querySelector('#contactTitle'),contactIntro=document.querySelector('#contactIntro'),contactIntent=document.querySelector('#contactIntent');
const contactCopy={follow:['Follow Hydra and stay informed.','Save your Search Profile and receive one considered weekly update about Hydra.'],advisor:['Talk to a Fourma advisor.','Your advisor will receive this Search Profile, Hydra research and the properties you viewed.'], 'view-all':['See all 17 matching homes.','Create your saved Search Profile and keep the complete Hydra research attached.'],property:['Ask about this property.','We’ll attach the property, your Search Profile and full location context to your request.']};
function openContact(intent){const copy=contactCopy[intent]||contactCopy.advisor;contactTitle.textContent=copy[0];contactIntro.textContent=copy[1];contactIntent.value=intent;document.querySelector('#contactForm').style.display='grid';document.querySelector('#formSuccess').classList.remove('show');overlay.classList.add('open');overlay.setAttribute('aria-hidden','false')}
document.addEventListener('click',e=>{const contact=e.target.closest('[data-contact]');if(contact){e.preventDefault();openContact(contact.dataset.contact)}if(e.target.closest('[data-close-modal]')||e.target===overlay){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true')}if(e.target.closest('[data-close-drawer]')||e.target.id==='drawerBackdrop')closeDrawer()});
document.querySelector('#contactForm').addEventListener('submit',e=>{e.preventDefault();e.target.style.display='none';document.querySelector('#formSuccess').classList.add('show')});

const propertyData=[['KAMINI · HYDRA','Stone house above the harbour','€2,450,000','4','3','246','Quiet setting, guest privacy and uninterrupted sea views.'],['HYDRA TOWN · HYDRA',"Restored captain's residence",'€2,100,000','3','3','198','Historic character in the social centre of island life.'],['MANDRAKI · HYDRA','Waterfront summer house','€1,780,000','3','2','174','Direct sea access and exceptional privacy at the island edge.']];
const drawer=document.querySelector('#propertyDrawer'),backdrop=document.querySelector('#drawerBackdrop');
function openProperty(index){const p=propertyData[index];document.querySelector('#drawerLocation').textContent=p[0];document.querySelector('#drawerTitle').textContent=p[1];document.querySelector('#drawerPrice').textContent=p[2];document.querySelector('#drawerIndex').textContent='0'+(index+1)+' / 03';const facts=document.querySelectorAll('.drawer-facts b');facts[0].textContent=p[3];facts[1].textContent=p[4];facts[2].textContent=p[5];document.querySelector('.drawer-fit h3').textContent=p[6];drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.property-card').forEach(card=>{card.addEventListener('click',()=>openProperty(Number(card.dataset.property)));card.addEventListener('keydown',e=>{if(e.key==='Enter')openProperty(Number(card.dataset.property))})});
renderProfile();renderChoices();
